[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bxcan = "0.7.0"
postcard = "1.0.8"
serde = { version = "1.0.202", features = ["derive"], default-features = false }
